cc_test(
    name = "offset_ptr_test",
    srcs = [
        "offset_ptr_test.cpp",
        "offset_ptr_test.hpp",
        "NonPrimitive.hpp"
    ],
    deps = [
         "@gtest//:gtest_main",
         "//src:offset_ptr"
    ]
)
